# Site settings
title: About me
description: 'Taller de Computación.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://the-mvm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Anneliese Nicolle Martínez Sánchez # add your name
author-pic: ![Tarea 995](Github.jpg)
about-author: Tengo 17 años y actualmente me encuentro cursando la carrera de Innovación Empresarial en la Universidad del Caribe. Me considero una persona creativa, proactiva y con gran interés en el desarrollo de nuevas ideas que generen un impacto positivo en la sociedad.
Entre mis principales habilidades se encuentran la comunicación efectiva, el trabajo en equipo y la capacidad de adaptación a diferentes entornos. Disfruto aprender constantemente y enfrentar nuevos retos que me permitan crecer tanto a nivel académico como personal.
En cuanto a mis intereses personales, me apasiona el arte en sus distintas expresiones, especialmente el baile y la cocina, actividades que practico con frecuencia y que me permiten expresar mi creatividad. También me interesa el emprendimiento, la sostenibilidad y la tecnología aplicada a los negocios, áreas en las que busco desarrollarme profesionalmente.

# Contact links
email: anneliesenmartimez@gmail.com # Add your Email address
phone: # 9984960026
website: https://Anneliesemartinez.github.io # Add your website
linkedin: Anneliese # Add your Linkedin handle
github: Anneliesemartinez # Add your Github handle
twitter: '@MvmThe' # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username
stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
